### ISSUE TITLE
Solar - Images created in solar can't be set to Dynamic

### ISSUE THREAD

**Issue by mrtoikka** [rlxone/Equinox#46]
Used 16 images to create a dynamic image.

Used solar tool to identify alt-az for each each photo's time/location.

Created dynamic image, then saved to Pictures directory in user profile.

In MacOS settings, added Pictures directory and selected dynamic image created by Equinox.

Cannot select Dynamic in settings, only Fill/Stretch/Center/etc.

Also, it appears that the primary image used for thumbnail is the same image that gets set as background when trying to select the image for a background.

Using Equinox 2.0 (5) on Ventura 13.4.1

**Comment by mrtoikka** [comment]
I found that if I set 1 of the 16 images to also be a light image and another 1 of the 16 to be a dark image, then the dynamic image I generate will allow me to select Dynamic/Light/Dark when setting wallpaper in macOS settings. However, it still uses the image I select as the primary image/thumbnail. Not even changing system time changes the image.

**Comment by rlxone** [comment]
Hi, @mrtoikka!
Looks like you've run into macOS bug. I mentioned it in the FAQ on the ReadMe.

<hr>

FAQ:

- Q: I set up my wallpaper, but it won't change over time. Looks like it doesn't work.

- A: Due to macOS bug you need to set «Dynamic» type in your «Desktop & Screen Saver» macOS Preferences before you set the wallpaper.

   - Open «Desktop & Screen Saver» macOS Preferences.

   - Choose any «Dynamic Desktop» wallpaper and set it’s type to «Dynamic».

   - Right click on your wallpaper, then «Services» -> «Set Desktop Picture»

<hr>

or just simply use `Set` option right after you create a new wallpaper in Equinox

<img width="762" alt="image" src="https://github.com/rlxone/Equinox/assets/8312717/08cd2ed8-fcd8-41ae-87a2-8bd6341e0898">

**Comment by rlxone** [comment]
feel free to report if its still an issue!
